version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'â¬†ï¸ dep:'
      prefix-development: 'â¬†ï¸ğŸ”¨ dev-dep:'
    assignees:
      - "shanpriyan"
    reviewers:
      - "shanpriyan"
    open-pull-requests-limit: 50
    rebase-strategy: auto
